#!/usr/bin/with-contenv bash
# chown -R aegir:aegir /var/aegir/
echo "starting hostmaster ...."
set -ex
echo "implement hostmaster checking...."
gosu aegir bash /etc/services.d/hostmaster/hostmaster.sh
echo "setup hostmaster crontab ..."
bash /etc/services.d/hostmaster/crontab.sh
gosu aegir drush cc drush
echo "hostmaster delete queue ..."
gosu aegir drush @hostmaster sqlq "delete from semaphore where name like 'hosting_queue_%_running'"
echo "setup hostmaster hosting-queued ..."
exec gosu aegir drush @hostmaster hosting-queued
