#!/usr/bin/with-contenv bash
echo "starting hostmaster ...."
set -ex
echo "implement hostmaster checking...."
gosu aegir bash /usr/local/bin/hostmaster.sh
echo "setup hostmaster crontab ..."
bash /usr/local/bin/crontab.sh
gosu aegir drush cc drush
echo "hostmaster delete queue lock ..."
gosu aegir drush @hostmaster sqlq "delete from semaphore where name like 'hosting_queue_%_running'"
